# Generated by Django 4.1.1 on 2022-09-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='fecha',
        ),
    ]
