# Generated by Django 4.1.1 on 2022-09-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_link_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
